export const allProductData = [
  {
    images: [
      "https://www.ikea.com/in/en/images/products/gammalbyn-3-seat-sofa-grey__0868926_pe781434_s5.jpg?f=xl",
    ],
    title: "3-seat sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/ektorp-3-seat-sofa-with-chaise-longue-kilanda-dark-blue__1194861_pe902093_s5.jpg?f=xl",
    ],
    title: "3-seat sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/jaettebo-u-shaped-sofa-7-seat-with-chaise-longue-right-with-headrests-tonerud-grey__1179836_pe896109_s5.jpg?f=xl",
    ],
    title: "L-shaped sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/gammalbyn-3-seat-sofa-grey__0868926_pe781434_s5.jpg?f=xl",
    ],
    title: "3-seat sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/jaettebo-u-shaped-sofa-7-seat-with-chaise-longue-right-with-headrests-tonerud-grey__1179836_pe896109_s5.jpg?f=xl",
    ],
    title: "L-shaped sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/gammalbyn-3-seat-sofa-grey__0868926_pe781434_s5.jpg?f=xl",
    ],
    title: "3-seat sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/jaettebo-u-shaped-sofa-7-seat-with-chaise-longue-right-with-headrests-tonerud-grey__1179836_pe896109_s5.jpg?f=xl",
    ],
    title: "L-shaped sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/gammalbyn-3-seat-sofa-grey__0868926_pe781434_s5.jpg?f=xl",
    ],
    title: "3-seat sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/jaettebo-u-shaped-sofa-7-seat-with-chaise-longue-right-with-headrests-tonerud-grey__1179836_pe896109_s5.jpg?f=xl",
    ],
    title: "L-shaped sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/gammalbyn-3-seat-sofa-grey__0868926_pe781434_s5.jpg?f=xl",
    ],
    title: "3-seat sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/jaettebo-u-shaped-sofa-7-seat-with-chaise-longue-right-with-headrests-tonerud-grey__1179836_pe896109_s5.jpg?f=xl",
    ],
    title: "L-shaped sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
  {
    images: [
      "https://www.ikea.com/in/en/images/products/gammalbyn-3-seat-sofa-grey__0868926_pe781434_s5.jpg?f=xl",
    ],
    title: "3-seat sofa",
    price: 20990,
    category: "",
    colors: [],
    description: "",
    discountedPrice: 0,
    features: "",
    id: 7,
    label: "",
    slug: "",
  },
];
